vich_uploader:
    db_driver: orm
    storage:   gaufrette

    mappings:
        assets:
            inject_on_load: true
            uri_prefix:         https://flipapop-images.s3.amazonaws.com
            upload_destination: images_fs
            delete_on_update:   false
            delete_on_remove:   false