# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-browsers
      - image: circleci/postgres:10
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
        environment:
          POSTGRES_USER: root

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist
      - run: php bin/console fos:elastica:populate,

      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      - run: ./bin/phpunit --log-junit ~/phpunit/junit.xml
      - store_test_results:
                path: ~/phpunit
      - store_artifacts:
                path: ~/phpunit
      